services:
  api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    command: api
    ports:
      - "8000:8000"
    volumes:
      - ../mlruns:/app/mlruns
      - ../data:/app/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - ../mlruns:/mlruns
      - ../data:/data
    command: mlflow server --host 0.0.0.0 